export const LOAD_CUSTOMERS_SUCCESS = "LOAD_CUSTOMERS_SUCCESS";
export const LOAD_CUSTOMERS_ERROR = "LOAD_CUSTOMERS_ERROR";
export const FIND_CUSTOMERS_SUCCESS = "FIND_CUSTOMERS_SUCCESS";
export const FIND_CUSTOMERS_ERROR = "FIND_CUSTOMERS_ERROR";