//Customer
export const LOAD_CUSTOMERS_SUCCESS = "LOAD_CUSTOMERS_SUCCESS";
export const LOAD_CUSTOMERS_ERROR = "LOAD_CUSTOMERS_ERROR";
export const FIND_CUSTOMERS_SUCCESS = "FIND_CUSTOMERS_SUCCESS";
export const FIND_CUSTOMERS_ERROR = "FIND_CUSTOMERS_ERROR";

//Dealer
export const LOAD_DEALERS_SUCCESS = "LOAD_DEALERS_SUCCESS";
export const LOAD_DEALERS_ERROR = "LOAD_DEALERS_ERROR";

//Agreement
export const ADD_AGREEMENT_SUCCESS = "ADD_AGREEMENT_SUCCESS";
export const ADD_AGREEMENT_ERROR = "ADD_AGREEMENT_ERROR";